on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: ./
      with:
        who-to-greet: 'PureScript User'
    # Use the output from the `hello` step
    - name: Get a description of the PureScript language
      run: echo "What is PureScript? ${{ steps.hello.outputs.what-is-purescript }}"
